[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "The Career Development Mindset for Diversity and Inclusion: Building Empathy and Connection for Professional Growth"
